delete job definition after job is submitted
base2genomics/batchit pull request #2
Opened 2017-12-07 20:58 UTC by dtenenba

This avoids the proliferation of job definitions that are used only once. At my institute, with potentially hundreds of users sharing the same AWS Batch account, not having this could create a huge number of job definitions.

2017-12-07 21:21 UTC, brentp requested changes
looks good. just a couple minor nits.

2017-12-07 21:21 UTC, brentp commented on submit/submit.go
> +	if err != nil {
just return err here since you return nil otherwise anyway.

2017-12-07 21:21 UTC, brentp commented on submit/submit.go
> +	defer deleteJobDefinition(b, ro)
can you add a comment above this reminding us the we're discarding the error. doesn't matter most likely, but I want to remember that we're explicitly ignoring it for now.

2017-12-07 23:27 UTC, dtenenba commented
OK, just pushed those changes.

2017-12-08 00:42 UTC, merged

2017-12-08 00:42 UTC, brentp commented
thank you.